# For Development with DecapCMS
local_backend: true

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "src/assets/"
public_folder: "/assets/"

collections:
    - name: "pages"
      label: "Pages"
      files:
        - name: "home"
          label: "Home"
          file: "src/pages/home.md"
          fields:
            - label: "Home Hero Right"
              name: "homeHeroRight"
              widget: "object"
              fields:
                - { label: "Title", name: "heroTitle", widget: "string" }
                - { label: "Subtitle", name: "heroSubTitle", widget: "string" }
                - { label: "Content", name: "heroContent", widget: "markdown" }
            - { label: "Banner text", name: "bannerText", widget: "markdown" }
            - label: "Home Hero Left"
              name: "homeHeroLeft"
              widget: "object"
              fields:
                - { label: "Title", name: "heroTitle", widget: "string" }
                - { label: "Content", name: "heroContent", widget: "markdown" }
            - label: "Home Section Header"
              name: "homeSectionHeader"
              widget: "object"
              fields:
                - { label: "Title", name: "sectionHeaderTitle", widget: "string" }
                - { label: "SubText", name: "sectionHeaderSubText", widget: "text" }
                - { label: "SubTitle", name: "sectionHeaderSubTitle", widget: "string" }
        - name: "mission"
          label: "Mission"
          file: "src/pages/mission.md"
          fields:
            - label: "Mission Hero"
              name: "missionHero"
              widget: "object"
              fields:
                - { label: "Hero Title", name: "heroTitle", widget: "string" }
                - { label: "Hero Content", name: "heroContent", widget: "markdown" }
                - { label: "Date text", name: "dateText", widget: "string" }
                - { label: "Link text", name: "linkText", widget: "string" }
                - { label: "Link file", name: "linkFile", widget: "file", allow_multiple: false}
        - name: "membership"
          label: "Membership"
          file: "src/pages/membership.md"
          fields:
            - { label: "Membership Header", name: "membershipHeader", widget: "string" }
            - { label: "Membership Announcement", name: "membershipAnnouncement", widget: "markdown", editor-blocks: ["file"]}
            - { label: "Membership Content", name: "body", widget: "markdown" }
        - name: "contact"
          label: "Contact"
          file: "src/pages/contact.md"
          fields:
            - { label: "Contact Header", name: "contactHeader", widget: "string" }
            - { label: "Contact Description", name: "contactDescription", widget: "string" }
        - name: "story"
          label: "Story"
          file: "src/pages/story.md"
          fields:
            - { label: "Hero Title", name: "heroTitle", widget: "string" }
            - { label: "Hero Content", name: "body", widget: "markdown" }

    - label: "Board Members"
      name: "boardMemberItem"
      folder: "src/pages/board-members"
      slug: "{{memberName}}-{{year}}-{{month}}-{{day}}"
      create: true
      fields:
        - { label: "Member Name", name: "memberName", widget: "string" }
        - { label: "Member Organization Name", name: "memberOrganization", widget: "string" }
        - { label: "Member Role", name: "memberRole", widget: "string" }
        - { label: "Member Image", name: "memberImage", widget: "image" }
        - { label: "Member Image Alt", name: "memberImageAlt", widget: "string" }
        - { label: "Order", name: "order", widget: "number" }

    - label: "Organizations"
      name: "orgItem"
      folder: "src/pages/organizations"
      slug: "{{organizationName}}-{{year}}-{{month}}-{{day}}"
      create: true
      fields:
        - { label: "Organization Name", name: "organizationName", widget: "string" }
        - { label: "Organization Description", name: "organizationDescription", widget: "text" }
        - { label: "Organization Link", name: "linkURL", widget: "string" }
        - { label: "Organization Image", name: "organizationImage", widget: "image" }
        - { label: "Organization Alt", name: "organizationAlt", widget: "string" }
        - { label: "Founding Member", name: "foundingMember", widget: "boolean", default: false }






