local_backend:
  url: http://localhost:8082/api/v1

backend:
  name: git-gateway

# backend:
#   name: github
#   repo: kindsys/digital-services-coalition
#   branch: main

media_folder: "src/assets/img/"
public_folder: "/assets/img/"

collections:
    - label: "Board Members"
      name: "boardMemberItem"
      folder: "src/pages/board-members"
      slug: "{{memberName}}-{{year}}-{{month}}-{{day}}"
      create: true
      fields:
        - { label: "Member Name", name: "memberName", widget: "string" }
        - { label: "Member Organization Name", name: "memberOrganization", widget: "string" }
        - { label: "Member Role", name: "memberRole", widget: "string" }
        - { label: "Member Image", name: "memberImage", widget: "image" }
        - { label: "Member Image Alt", name: "memberImageAlt", widget: "string" }
        - { label: "Order", name: "order", widget: "number" }

    - label: "Organizations"
      name: "orgItem"
      folder: "src/pages/organizations"
      slug: "{{organizationName}}-{{year}}-{{month}}-{{day}}"
      create: true
      fields:
        - { label: "Organization Name", name: "organizationName", widget: "string" }
        - { label: "Organization Description", name: "organizationDescription", widget: "text" }
        - { label: "Organization Link", name: "linkURL", widget: "string" }
        - { label: "Organization Image", name: "organizationImage", widget: "image" }
        - { label: "Organization Alt", name: "organizationAlt", widget: "string" }
        - { label: "Founding Member", name: "foundingMember", widget: "boolean", default: false }





    - name: "pages"
      label: "Pages"
      files:
        - name: "home"
          label: "Home"
          file: "src/pages/home.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Banner text", name: "bannerText", widget: "string" }
        - name: "mission"
          label: "Mission"
          file: "src/pages/mission.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - label: "Mission header"
              name: "missionHeader"
              widget: "object"
              fields:
                - { label: "Date text", name: "dateText", widget: "string" }
                - { label: "Link text", name: "linkText", widget: "string" }
        - name: "membership"
          label: "Membership"
          file: "src/pages/membership.md"
          fields:
            - { label: "Membership header", name: "membershipHeader", widget: "string" }
            - { label: "Membership announcement", name: "membershipAnnouncement", widget: "markdown"}
            - { label: "Membership content", name: "body", widget: "markdown" }
        - name: "story"
          label: "Story"
          file: "src/pages/story.md"
          fields:
            - { label: "Hero Title", name: "heroTitle", widget: "string"}
            - { label: "Hero Content", name: "body", widget: "markdown"}




